test_bigquery:
  outputs:
    dev:
      dataset: prefect_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: exture-owneddata-all
      threads: 4
      type: bigquery
  target: dev
